#!/bin/bash
#
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

cd "$(readlink -f "$(dirname "$0")")"

if grep -IEn '[[:space:]]+$' . -r \
        --exclude-dir=.angular \
        --exclude-dir=.git \
        --exclude-dir=dist \
        --exclude-dir=karma-firefox-profile \
        --exclude-dir=node_modules \
        --exclude='*~'; then
  echo "Trailing whitespace found."
  exit 1
fi

input=src/app/gql/parser_impl.pegjs
output="${input%pegjs}js"
if ! diff -u3 "$output" <(npx peggy --allowed-start-rules start,node,edge,identifier,expression < "$input"); then
  echo "$output is out of date; run peggy."
  exit 1
fi

npm run ng test -- --watch=false
npm run prettier-check
